### ISSUE TITLE
 error: could not load the project file.

### ISSUE THREAD

**Issue by it19862** [robinrodricks/ScintillaNET.Demo#1]
I open the project.
I get an error

C: \ vs \ csh \ 03 \ ScintillaNET.Demo.csproj: error: could not load the project file. The file 'C: \ vs \ csh \ 03 \ ScintillaNET.Demo.csproj' was not found. C: \ vs \ csh \ 03 \ ScintillaNET.Demo.csproj

How to fix the error?

**Comment by apuchkov** [comment]
I created a PR #2 to fix this issue.

**Comment by robinrodricks** [comment]
Sorry I've been a bit busy. I'll check this soon.

**Comment by nooogle** [comment]
There are 2 solution files.. the inner-most one opens fine for me:

ScintillaNET.Demo\ScintillaNET.Demo.sln

(Looks like the solution file and properties are duplicated in the current master branch).
