### ISSUE TITLE
64 bit issue in "Lines"

### ISSUE THREAD

**Issue by p4spares** [robinrodricks/ScintillaNET.Demo#6]
hi, i'm trying to use ScintillaNet on a 64 bit project using the "Lines" property.

here is the case:

        private void Form1_Load(object sender, EventArgs e)
        {
            ScintillaNET.Scintilla s = new ScintillaNET.Scintilla();
            s.Dock = DockStyle.Fill;
            panel1.Controls.Add(s);
            s.Text = "aaaaa\nbbbbb\n";
            textBox1.Text = s.Lines.Count.ToString();
        }

under x86 the value is "3" as expected.
under x64 the value is "1".

if you need more information, let me know.
thanks,
David

**Comment by robinrodricks** [comment]
Ask on ScintillaNet project.
